spring:
  profiles:
    active: prod
  application:
    name: A-Blog-System
server:
  port: 9898

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false


