spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://a-blog-system-db.mysql.database.azure.com:3306/a_blog_system?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${azure-mysql-db-user}
    password: ${azure-mysql-db-password}
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池配置
    hikari:
      connection-timeout: 50000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: DB-Pool



