spring:
  datasource:
    url: jdbc:h2:mem:a_blog_system;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池配置
    hikari:
      connection-timeout: 50000
#      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: DB-Pool
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always
      platform: mysql
