name: Maven Build

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: |
          mkdir /var/log/blog-system
          mvn -B test

#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn -B --skipTests package --file pom.xml
